//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class licenta : DbContext
    {
        public licenta()
            : base("name=licenta")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<Difficulty> Difficulties { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<TrailDifficulty> TrailDifficulties { get; set; }
        public virtual DbSet<TrailReview> TrailReviews { get; set; }
        public virtual DbSet<Trail> Trails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TouristGuide> TouristGuides { get; set; }
        public virtual DbSet<TouristGuideTrail> TouristGuideTrails { get; set; }
    }
}
