//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public double Stars { get; set; }
        public int UserId { get; set; }
        public int TrailId { get; set; }
    
        public virtual Trail Trail { get; set; }
        public virtual User User { get; set; }
    }
}
