//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristGuide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TouristGuide()
        {
            this.TouristGuideTrails = new HashSet<TouristGuideTrail>();
        }
    
        public int Id { get; set; }
        public string Discover { get; set; }
        public string Promote { get; set; }
        public string Camping { get; set; }
        public string Fire { get; set; }
        public string Deviation { get; set; }
        public string Noise { get; set; }
        public string Environment { get; set; }
        public string Rules { get; set; }
        public string Garbage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouristGuideTrail> TouristGuideTrails { get; set; }
    }
}
